###########
# site.title, site.url, site.author.name

title:   Razones para ser optimista
author:  
  name:  'Yrjö'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /noticias
url:  'https://yrjo.tk'


########
# more settings

timezone: Europe/Madrid
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md
- Gemfile
- .gitignore


safe: true
lsi: false

plugins: [jekyll-paginate]

# PAGINATION
paginate: 5
paginate_path: "/page:num"

